#[derive(Debug, Clone)]
pub struct PackageFaq {
    pub question: &'static str,
    pub answer: &'static str,
}

#[derive(Debug, Clone)]
pub struct RelatedPackage {
    pub label: &'static str,
    pub name: &'static str,
    pub href: &'static str,
    pub note: &'static str,
}

#[derive(Debug, Clone)]
pub struct WebPackage {
    pub slug: &'static str,
    pub name: &'static str,
    pub short_name: &'static str,
    pub catalog_name: &'static str,
    pub item_code: &'static str,
    pub category: &'static str,
    pub price: &'static str,
    pub price_number: &'static str,
    pub positioning: &'static str,
    pub audience: Vec<&'static str>,
    pub core_message: &'static str,
    pub description: &'static str,
    pub inclusions: Vec<&'static str>,
    pub differentiator: &'static str,
    pub business_problem: &'static str,
    pub outcomes: Vec<&'static str>,
    pub example_structure: Vec<&'static str>,
    pub addons: Vec<&'static str>,
    pub pricing_note: &'static str,
    pub faqs: Vec<PackageFaq>,
    pub related: Vec<RelatedPackage>,
    pub meta_title: &'static str,
    pub meta_description: &'static str,
    pub icon: &'static str,
}

#[derive(Debug, Clone)]
pub struct WebPackageFamily {
    pub name: &'static str,
    pub packages: Vec<WebPackage>,
}

impl WebPackage {
    pub fn url(&self) -> String {
        format!("/packages/web-design-development/{}", self.slug)
    }

    pub fn canonical_url(&self) -> String {
        format!("https://lkprofessionals.com{}", self.url())
    }

    pub fn quote_url(&self) -> String {
        format!("/request-quote?package={}&source={}", self.slug, self.url())
    }

    pub fn whatsapp_url(&self) -> String {
        let message = format!(
            "Hello LKProfessionals, I want to discuss the {} starting from {}. Source: {}",
            self.name,
            self.price,
            self.url()
        )
        .replace(' ', "%20")
        .replace(':', "%3A")
        .replace('/', "%2F")
        .replace(',', "%2C");

        format!("https://wa.me/94761234321?text={message}")
    }
}

pub fn web_design_family() -> WebPackageFamily {
    WebPackageFamily {
        name: "Web Design & Development Packages",
        packages: vec![
            WebPackage {
                slug: "digital-footprint",
                name: "Digital Footprint",
                short_name: "Digital Footprint",
                catalog_name: "Digital Footprint - Web Design Package",
                item_code: "LKP-WEB-DF-001",
                category: "Entry-level professional website",
                price: "LKR 10,000+",
                price_number: "10000",
                positioning: "Entry-level professional online presence.",
                audience: vec![
                    "Freelancers",
                    "Solo entrepreneurs",
                    "Consultants",
                    "Professionals",
                    "Personal portfolios",
                    "Small service providers",
                ],
                core_message: "Build your professional presence online.",
                description: "Digital Footprint is an affordable professional website package for freelancers, solo entrepreneurs, professionals, and small businesses establishing their first online presence.",
                inclusions: vec![
                    "Professionally designed single-page website",
                    "Responsive desktop, tablet, and mobile design",
                    "About or introduction section",
                    "Services or expertise section",
                    "Contact section",
                    "WhatsApp integration",
                    "Social media links",
                    "Basic on-page SEO",
                    "Performance-focused development",
                    "SSL/HTTPS configuration",
                ],
                differentiator: "A focused single-page website that gives a professional, searchable destination without a larger initial build.",
                business_problem: "You need a credible online presence customers can visit, but a multi-page website would be more than the current requirement.",
                outcomes: vec![
                    "A professional page you can share from profiles, proposals, and social channels",
                    "Clear contact and WhatsApp paths for interested visitors",
                    "A practical foundation that can expand into a larger website later",
                ],
                example_structure: vec![
                    "Hero with your offer and primary contact action",
                    "About or professional introduction",
                    "Services, expertise, or portfolio summary",
                    "Contact, WhatsApp, and social links",
                ],
                addons: vec![
                    "Domain and hosting",
                    "Additional pages",
                    "Advanced forms",
                    "Booking, payment, or custom functionality",
                ],
                pricing_note: "Starting from LKR 10,000. Domain, hosting, additional pages, and advanced functionality can be added separately after scope review.",
                faqs: vec![
                    faq(
                        "Is this only one page?",
                        "Yes. Digital Footprint is designed as a professional single-page website. Additional pages can be quoted separately.",
                    ),
                    faq(
                        "Is domain and hosting included?",
                        "Domain and hosting can be added separately for this entry-level package.",
                    ),
                    faq(
                        "Can I upgrade later?",
                        "Yes. This package can grow into LaunchPad, Momentum, or a custom website when your requirements expand.",
                    ),
                ],
                related: vec![related(
                    "Upgrade",
                    "LaunchPad",
                    "/packages/web-design-development/launchpad",
                    "Move to a complete first business website with multiple pages and hosting included.",
                )],
                meta_title: "Digital Footprint Web Design Package Sri Lanka | LKProfessionals",
                meta_description: "Digital Footprint starts from LKR 10,000 for freelancers, consultants, portfolios, and small service providers that need a professional single-page website.",
                icon: "fa-id-badge",
            },
            WebPackage {
                slug: "launchpad",
                name: "LaunchPad",
                short_name: "LaunchPad",
                catalog_name: "LaunchPad - Business Website Package",
                item_code: "LKP-WEB-LP-002",
                category: "Complete first business website",
                price: "LKR 30,000+",
                price_number: "30000",
                positioning: "A complete first business website for startups and small businesses.",
                audience: vec![
                    "Startups",
                    "Small businesses",
                    "Professional service providers",
                    "Growing companies",
                ],
                core_message: "Launch your business with a professional website built for growth.",
                description: "LaunchPad gives startups and small businesses a structured, responsive business website with the essentials needed for a credible launch.",
                inclusions: vec![
                    "Up to 6 pages",
                    "Modern custom responsive design",
                    "Mobile, tablet, and desktop optimisation",
                    "Home, About, Services, and Contact pages",
                    "Contact and enquiry functionality",
                    "WhatsApp integration",
                    "Social media integration",
                    "Basic on-page SEO",
                    "Blog functionality",
                    "Administration dashboard",
                    "SSL/HTTPS",
                    "Performance optimisation",
                    "Domain and hosting for first year",
                ],
                differentiator: "A complete first business website with domain, hosting, blog, dashboard, and core enquiry flows included.",
                business_problem: "Your business needs more than a profile page: customers need to understand your company, services, and how to enquire.",
                outcomes: vec![
                    "A launch-ready website with clear service and contact pages",
                    "A content foundation that can support future SEO and blog updates",
                    "A professional platform that can expand as the company grows",
                ],
                example_structure: vec![
                    "Home",
                    "About",
                    "Services",
                    "Service detail or business-specific page",
                    "Blog",
                    "Contact",
                ],
                addons: vec![
                    "Extra pages",
                    "Copywriting",
                    "Advanced SEO",
                    "Booking or payment features",
                    "Ongoing maintenance",
                ],
                pricing_note: "Starting from LKR 30,000 with domain and hosting for the first year included within the defined package scope.",
                faqs: vec![
                    faq(
                        "How many pages are included?",
                        "LaunchPad includes up to 6 pages.",
                    ),
                    faq(
                        "Is a blog included?",
                        "Yes. Blog functionality and administration dashboard access are included.",
                    ),
                    faq(
                        "Who is LaunchPad best for?",
                        "It is best for startups, small businesses, professional services, and growing companies launching a complete first website.",
                    ),
                ],
                related: vec![
                    related(
                        "Simpler",
                        "Digital Footprint",
                        "/packages/web-design-development/digital-footprint",
                        "Use this if a single-page online presence is enough.",
                    ),
                    related(
                        "Local alternative",
                        "Local Spark",
                        "/packages/web-design-development/local-spark",
                        "Use this if nearby customer discovery is the main priority.",
                    ),
                    related(
                        "Upgrade",
                        "Momentum",
                        "/packages/web-design-development/momentum",
                        "Use this when you need a stronger platform with more pages and growth structure.",
                    ),
                ],
                meta_title: "LaunchPad Business Website Package Sri Lanka | LKProfessionals",
                meta_description: "LaunchPad starts from LKR 30,000 for startups and small businesses needing a complete responsive website with hosting, blog, SEO basics, and dashboard.",
                icon: "fa-rocket",
            },
            WebPackage {
                slug: "local-spark",
                name: "Local Spark",
                short_name: "Local Spark",
                catalog_name: "Local Spark - Local Business Website Package",
                item_code: "LKP-WEB-LS-003",
                category: "Local business website",
                price: "LKR 40,000+",
                price_number: "40000",
                positioning: "A website designed to help location-based businesses attract nearby customers.",
                audience: vec![
                    "Restaurants",
                    "Cafes",
                    "Salons",
                    "Local retailers",
                    "Repair services",
                    "Construction businesses",
                    "Tuition centres",
                    "Professional services",
                    "Location-based businesses",
                ],
                core_message: "Get found locally. Turn searches into real customers.",
                description: "Local Spark is built for location-based businesses that need service-area content, map visibility, click-to-call paths, WhatsApp, and local SEO foundations.",
                inclusions: vec![
                    "Up to 8 pages",
                    "Custom responsive design",
                    "Mobile, tablet, and desktop optimisation",
                    "Service-focused pages",
                    "Location and service-area content",
                    "Google Maps integration",
                    "WhatsApp integration",
                    "Click-to-call functionality",
                    "Contact and enquiry forms",
                    "Social media integration",
                    "Local SEO foundation",
                    "Basic on-page SEO",
                    "Blog functionality",
                    "Administration dashboard",
                    "SSL/HTTPS",
                    "Performance optimisation",
                    "Domain and hosting for first year",
                ],
                differentiator: "Local SEO, service-area content, map integration, and mobile contact actions are treated as core requirements.",
                business_problem: "Nearby customers search before they call or visit, and your website needs to make location, services, and contact actions obvious.",
                outcomes: vec![
                    "Clear local service positioning",
                    "Easier phone, WhatsApp, map, and enquiry actions",
                    "A stronger base for local search visibility without ranking guarantees",
                ],
                example_structure: vec![
                    "Home with local value proposition",
                    "About",
                    "Services",
                    "Service areas or location page",
                    "Gallery or menu",
                    "Blog",
                    "Contact with map",
                    "Business-specific page",
                ],
                addons: vec![
                    "Google Business Profile support",
                    "Menu/catalog sections",
                    "Additional service-area pages",
                    "Review collection workflows",
                    "Local SEO campaign",
                ],
                pricing_note: "Starting from LKR 40,000. Final scope depends on number of locations, service areas, content needs, and integrations.",
                faqs: vec![
                    faq(
                        "Does Local Spark guarantee local rankings?",
                        "No. It creates a local SEO foundation, but search rankings depend on many factors outside a website build alone.",
                    ),
                    faq(
                        "Is Google Maps included?",
                        "Yes. Google Maps integration is included where a business location or service area is relevant.",
                    ),
                    faq(
                        "Can this work for service-area businesses?",
                        "Yes. It can support location and service-area content for businesses that visit customers instead of operating only from one shop.",
                    ),
                ],
                related: vec![
                    related(
                        "General alternative",
                        "LaunchPad",
                        "/packages/web-design-development/launchpad",
                        "Use this if local search is not the main requirement.",
                    ),
                    related(
                        "Growth alternative",
                        "Momentum",
                        "/packages/web-design-development/momentum",
                        "Use this when the business needs a broader growth website.",
                    ),
                ],
                meta_title: "Local Spark Local Business Website Package | LKProfessionals",
                meta_description: "Local Spark starts from LKR 40,000 for restaurants, salons, retailers, repair services, tuition centres, and other location-based businesses.",
                icon: "fa-location-dot",
            },
            WebPackage {
                slug: "momentum",
                name: "Momentum",
                short_name: "Momentum",
                catalog_name: "Momentum - Growth Website Package",
                item_code: "LKP-WEB-MO-004",
                category: "Growth website",
                price: "LKR 60,000+",
                price_number: "60000",
                positioning: "A stronger digital platform for businesses that have moved beyond a basic website.",
                audience: vec![
                    "Growing businesses",
                    "SMEs",
                    "Professional service companies",
                    "Established companies",
                    "Businesses expanding operations",
                ],
                core_message: "Accelerate your business growth online.",
                description: "Momentum supports businesses that need a more substantial website with richer service presentation, conversion-focused structure, analytics, and a scalable content base.",
                inclusions: vec![
                    "Up to 12 pages",
                    "Bespoke brand-focused design",
                    "Responsive optimisation",
                    "Advanced service or product presentation",
                    "Conversion-focused structure",
                    "Custom contact and enquiry forms",
                    "WhatsApp integration",
                    "Social media integration",
                    "Blog and content management",
                    "Administration dashboard",
                    "On-page SEO foundation",
                    "Google Analytics integration",
                    "Google Search Console setup",
                    "Performance optimisation",
                    "SSL/HTTPS",
                    "Domain and hosting for first year",
                ],
                differentiator: "A stronger business website shaped around growth, analytics, and richer service presentation.",
                business_problem: "A simple website is no longer enough because your services, buyer journey, and content needs have become more complex.",
                outcomes: vec![
                    "Clearer service architecture for buyers",
                    "Better enquiry paths across the site",
                    "Analytics and Search Console foundations for future improvement",
                ],
                example_structure: vec![
                    "Home",
                    "About",
                    "Core services",
                    "Individual service pages",
                    "Industries or solutions",
                    "Blog",
                    "Contact",
                    "Conversion landing page",
                ],
                addons: vec![
                    "SEO content program",
                    "CRM integration",
                    "Advanced conversion tracking",
                    "Case study pages",
                    "Extra service landing pages",
                ],
                pricing_note: "Starting from LKR 60,000. Final pricing depends on page count, content complexity, forms, and tracking needs.",
                faqs: vec![
                    faq(
                        "How is Momentum different from LaunchPad?",
                        "Momentum includes more page capacity, richer service presentation, analytics setup, and a stronger growth-oriented structure.",
                    ),
                    faq(
                        "Is Google Analytics included?",
                        "Yes. Google Analytics and Google Search Console setup are included.",
                    ),
                    faq(
                        "Can Momentum support future SEO work?",
                        "Yes. It creates a practical foundation for service pages, blog content, technical SEO, and future campaigns.",
                    ),
                ],
                related: vec![
                    related(
                        "Redesign alternative",
                        "Vanguard",
                        "/packages/web-design-development/vanguard",
                        "Use this if you already have an outdated website that needs modernisation.",
                    ),
                    related(
                        "Conversion upgrade",
                        "The Growth Engine",
                        "/packages/web-design-development/growth-engine",
                        "Use this if lead generation is the main priority.",
                    ),
                ],
                meta_title: "Momentum Growth Website Package Sri Lanka | LKProfessionals",
                meta_description: "Momentum starts from LKR 60,000 for SMEs and growing businesses that need a stronger website with analytics, SEO foundations, and conversion-focused structure.",
                icon: "fa-chart-line",
            },
            WebPackage {
                slug: "vanguard",
                name: "Vanguard",
                short_name: "Vanguard",
                catalog_name: "Vanguard - Premium Website Redesign Package",
                item_code: "LKP-WEB-VG-005",
                category: "Premium website redesign",
                price: "LKR 80,000+",
                price_number: "80000",
                positioning: "Premium redesign and modernisation for businesses that already have a website.",
                audience: vec![
                    "Established businesses",
                    "Professional firms",
                    "Organisations",
                    "Established brands",
                    "Companies with outdated websites",
                ],
                core_message: "You already have a website. Now build one worthy of the business you have become.",
                description: "Vanguard modernises outdated websites with premium UI/UX, improved navigation, migration planning, SEO foundations, and redirect planning for important existing URLs.",
                inclusions: vec![
                    "Complete website redesign",
                    "Up to 15 pages",
                    "Premium custom UI/UX",
                    "Brand-focused visual direction",
                    "Responsive optimisation",
                    "Existing content migration",
                    "Improved information architecture and navigation",
                    "Conversion-focused layouts",
                    "Advanced enquiry forms",
                    "WhatsApp and social integration",
                    "Blog and content management",
                    "Administration dashboard",
                    "Technical SEO foundation",
                    "On-page SEO foundation",
                    "Google Analytics",
                    "Google Search Console",
                    "Core Web Vitals and performance optimisation",
                    "SSL/HTTPS",
                    "Domain and hosting for first year",
                    "Redirect planning for important existing URLs",
                ],
                differentiator: "Redesign strategy, content migration, URL care, and modern UI/UX are handled together.",
                business_problem: "Your current website no longer reflects your business quality, and replacing it needs planning so important content and URLs are not ignored.",
                outcomes: vec![
                    "A more current and credible digital presence",
                    "Improved navigation and conversion paths",
                    "A planned transition from old pages to new ones",
                ],
                example_structure: vec![
                    "Redesigned home",
                    "About and team",
                    "Services and service detail pages",
                    "Case studies or proof pages",
                    "Insights or blog",
                    "Contact and enquiry workflows",
                ],
                addons: vec![
                    "Full content rewrite",
                    "Brand identity refresh",
                    "Advanced migration audit",
                    "CRM integration",
                    "Ongoing SEO retainer",
                ],
                pricing_note: "Starting from LKR 80,000. Final pricing depends on existing website size, migration requirements, redesign depth, and integrations.",
                faqs: vec![
                    faq(
                        "Will old URLs be considered?",
                        "Yes. Redirect planning for important existing URLs is included so the redesign has a cleaner transition path.",
                    ),
                    faq(
                        "Is this for new websites?",
                        "Vanguard is mainly for businesses that already have a website and need a premium redesign or modernisation.",
                    ),
                    faq(
                        "Can you migrate existing content?",
                        "Yes. Existing content migration is included within the agreed page and content scope.",
                    ),
                ],
                related: vec![
                    related(
                        "Lead generation alternative",
                        "The Growth Engine",
                        "/packages/web-design-development/growth-engine",
                        "Use this if the redesign is mainly about enquiries and conversion.",
                    ),
                    related(
                        "Corporate upgrade",
                        "The Flagship",
                        "/packages/web-design-development/flagship",
                        "Use this if the organisation needs a deeper corporate website.",
                    ),
                ],
                meta_title: "Vanguard Website Redesign Package Sri Lanka | LKProfessionals",
                meta_description: "Vanguard starts from LKR 80,000 for established businesses that need premium website redesign, migration planning, SEO foundations, and modern UI/UX.",
                icon: "fa-compass-drafting",
            },
            WebPackage {
                slug: "growth-engine",
                name: "The Growth Engine",
                short_name: "Growth Engine",
                catalog_name: "The Growth Engine - Lead Generation Website Package",
                item_code: "LKP-WEB-GE-006",
                category: "Lead generation website",
                price: "LKR 120,000+",
                price_number: "120000",
                positioning: "A website engineered primarily around lead generation and conversion.",
                audience: vec![
                    "Service businesses",
                    "B2B companies",
                    "Agencies",
                    "Professional firms",
                    "Established businesses dependent on online enquiries",
                ],
                core_message: "Your website should not just get visitors. It should generate business.",
                description: "The Growth Engine is for service-led businesses that need dedicated landing pages, strong CTAs, lead capture flows, CRM-ready structure, tracking, and SEO foundations.",
                inclusions: vec![
                    "Up to 20 pages",
                    "Conversion-focused custom website",
                    "Premium UI/UX",
                    "Responsive optimisation",
                    "Dedicated service landing pages",
                    "Strategic CTAs",
                    "Lead capture forms",
                    "Enquiry forms",
                    "WhatsApp integration",
                    "Click-to-call",
                    "CRM-ready lead capture structure",
                    "Blog and content management",
                    "Administration dashboard",
                    "Advanced on-page SEO foundation",
                    "Technical SEO",
                    "Conversion tracking",
                    "Google Analytics",
                    "Google Search Console",
                    "Core Web Vitals and performance optimisation",
                    "SSL/HTTPS",
                    "Domain and hosting for first year",
                ],
                differentiator: "Lead capture, landing pages, tracking, and conversion paths are built into the website architecture.",
                business_problem: "The business depends on enquiries, but the website needs clearer landing pages, CTAs, forms, and tracking before serious optimisation can happen.",
                outcomes: vec![
                    "More structured enquiry journeys",
                    "Tracking foundations for evaluating campaigns and content",
                    "Service pages designed around buyer intent without guaranteeing lead volume",
                ],
                example_structure: vec![
                    "Home",
                    "Core conversion pages",
                    "Dedicated service landing pages",
                    "Industries or use cases",
                    "Resource content",
                    "Lead capture forms",
                    "Contact and WhatsApp paths",
                ],
                addons: vec![
                    "CRM implementation",
                    "Paid campaign landing pages",
                    "Marketing automation",
                    "Advanced analytics dashboards",
                    "Ongoing SEO or content program",
                ],
                pricing_note: "Starting from LKR 120,000. Scope is shaped around services, lead flows, tracking requirements, and integration depth.",
                faqs: vec![
                    faq(
                        "Does this guarantee leads?",
                        "No. It creates a conversion-focused website foundation, but lead volume depends on traffic, offer, market demand, campaigns, and follow-up.",
                    ),
                    faq(
                        "Can forms connect to a CRM?",
                        "The package includes CRM-ready lead capture structure. Specific CRM integrations are scoped based on the platform and workflow.",
                    ),
                    faq(
                        "Is this suitable for B2B services?",
                        "Yes. It is a strong fit for B2B, agencies, professional firms, and service businesses dependent on online enquiries.",
                    ),
                ],
                related: vec![
                    related(
                        "Corporate alternative",
                        "The Flagship",
                        "/packages/web-design-development/flagship",
                        "Use this if authority and organisational depth matter as much as lead capture.",
                    ),
                    related(
                        "Commerce alternative",
                        "Omnichannel Commerce",
                        "/packages/web-design-development/omnichannel-commerce",
                        "Use this if online selling is the core requirement.",
                    ),
                ],
                meta_title: "Growth Engine Lead Generation Website Package | LKProfessionals",
                meta_description: "The Growth Engine starts from LKR 120,000 for service and B2B businesses needing lead generation website structure, landing pages, tracking, and SEO foundations.",
                icon: "fa-filter-circle-dollar",
            },
            WebPackage {
                slug: "omnichannel-commerce",
                name: "Omnichannel Commerce",
                short_name: "Omnichannel Commerce",
                catalog_name: "Omnichannel Commerce - Advanced E-Commerce Website Package",
                item_code: "LKP-WEB-OC-007",
                category: "Advanced e-commerce website",
                price: "LKR 180,000+",
                price_number: "180000",
                positioning: "Advanced e-commerce infrastructure for businesses serious about selling online.",
                audience: vec![
                    "Retailers",
                    "Product brands",
                    "Wholesalers",
                    "Established stores",
                    "Growing online businesses",
                    "Multi-channel sellers",
                ],
                core_message: "One business. Every channel. Built to sell.",
                description: "Omnichannel Commerce provides custom e-commerce design and development with catalogue, checkout, payments, order management, product SEO foundations, and commerce administration.",
                inclusions: vec![
                    "Custom e-commerce design and development",
                    "Responsive commerce experience",
                    "Product catalogue",
                    "Category management",
                    "Product variations and attributes",
                    "Shopping cart",
                    "Checkout",
                    "Customer accounts",
                    "Order management",
                    "Inventory management foundation",
                    "Payment gateway integration",
                    "Delivery and shipping configuration",
                    "Promotional codes and discounts",
                    "WhatsApp integration",
                    "Social integration",
                    "Product search and filtering",
                    "E-commerce administration dashboard",
                    "SEO-friendly product and category architecture",
                    "Technical SEO foundation",
                    "On-page SEO foundation",
                    "Google Analytics",
                    "Conversion tracking",
                    "Google Search Console",
                    "SSL/security",
                    "Performance optimisation",
                    "Domain and hosting for first year",
                ],
                differentiator: "Commerce architecture, product management, checkout, payments, shipping, and tracking are handled as one selling platform.",
                business_problem: "Selling online needs more than a catalogue page: customers need product discovery, checkout, payments, delivery information, and order management.",
                outcomes: vec![
                    "A structured online store foundation",
                    "Product and category pages built with SEO-friendly architecture",
                    "Admin tools for products, orders, and commerce operations",
                ],
                example_structure: vec![
                    "Storefront home",
                    "Product categories",
                    "Product detail pages",
                    "Cart and checkout",
                    "Customer account area",
                    "Order administration",
                    "Promotions and delivery information",
                ],
                addons: vec![
                    "Multi-vendor functionality",
                    "POS integration",
                    "ERP integration",
                    "Advanced inventory",
                    "Mobile applications",
                    "Marketplace integrations",
                ],
                pricing_note: "Starting from LKR 180,000. Additions such as POS, ERP, marketplace, multi-vendor, advanced inventory, and mobile apps are quoted separately.",
                faqs: vec![
                    faq(
                        "Are payment gateways included?",
                        "Payment gateway integration is included within the agreed payment provider and technical scope.",
                    ),
                    faq(
                        "Can this support product variations?",
                        "Yes. Product variations and attributes are part of the package foundation.",
                    ),
                    faq(
                        "Are ERP or POS integrations included?",
                        "ERP, POS, marketplace, and advanced inventory integrations are separately quoted because requirements vary widely.",
                    ),
                ],
                related: vec![related(
                    "Custom commerce requirements",
                    "Apex Custom",
                    "/packages/web-design-development/apex-custom",
                    "Use this if commerce needs move beyond a standard online store.",
                )],
                meta_title: "Omnichannel Commerce E-Commerce Website Package | LKProfessionals",
                meta_description: "Omnichannel Commerce starts from LKR 180,000 for retailers, wholesalers, and product brands needing advanced e-commerce design and development.",
                icon: "fa-cart-shopping",
            },
            WebPackage {
                slug: "flagship",
                name: "The Flagship",
                short_name: "Flagship",
                catalog_name: "The Flagship - Premium Corporate Website Package",
                item_code: "LKP-WEB-FS-008",
                category: "Premium corporate website",
                price: "LKR 250,000+",
                price_number: "250000",
                positioning: "A substantial, authoritative corporate digital presence.",
                audience: vec![
                    "Corporations",
                    "Large businesses",
                    "Institutions",
                    "NGOs",
                    "Engineering and construction companies",
                    "Professional firms",
                    "Established brands",
                ],
                core_message: "Your organisation has a reputation. Your website should carry it.",
                description: "The Flagship is a premium corporate website package for organisations that need deep information architecture, advanced CMS, structured data, resource centres, careers, projects, and stakeholder-friendly enquiry flows.",
                inclusions: vec![
                    "Up to 30 pages",
                    "Bespoke corporate website",
                    "Premium custom UI/UX",
                    "Corporate brand visual system",
                    "Advanced responsive design",
                    "Complex information architecture",
                    "Services, industries, and solutions sections",
                    "Projects, portfolio, or case studies",
                    "Leadership and team profiles",
                    "Careers and recruitment",
                    "News, insights, or resource centre",
                    "Advanced enquiry workflows",
                    "WhatsApp and social integration",
                    "Advanced CMS",
                    "Administration dashboard",
                    "Technical SEO",
                    "On-page SEO",
                    "Structured data",
                    "Google Analytics",
                    "Google Search Console",
                    "Conversion and event tracking",
                    "Core Web Vitals and performance optimisation",
                    "SSL/security",
                    "Domain and hosting for first year",
                ],
                differentiator: "Corporate-grade structure for authority, recruitment, projects, resources, and multiple stakeholder journeys.",
                business_problem: "The organisation has complex services, proof, teams, resources, and audiences that need a substantial website rather than a simple brochure site.",
                outcomes: vec![
                    "A stronger corporate presence for buyers, partners, recruits, and stakeholders",
                    "Scalable content areas for projects, insights, and careers",
                    "Structured data and technical foundations for long-term visibility",
                ],
                example_structure: vec![
                    "Corporate home",
                    "About and leadership",
                    "Services, industries, and solutions",
                    "Projects or case studies",
                    "Careers",
                    "News or resources",
                    "Advanced contact and enquiry workflows",
                ],
                addons: vec![
                    "Multilingual functionality",
                    "Portals",
                    "API integrations",
                    "Advanced databases",
                    "Custom business systems",
                ],
                pricing_note: "Starting from LKR 250,000. Multilingual features, portals, API integrations, advanced databases, and custom systems are quoted separately.",
                faqs: vec![
                    faq(
                        "Who is The Flagship for?",
                        "It is for corporations, institutions, NGOs, large businesses, and established brands that need a substantial corporate website.",
                    ),
                    faq(
                        "Is structured data included?",
                        "Yes. Structured data is included where it is appropriate for the visible content and page types.",
                    ),
                    faq(
                        "Can this include careers and resources?",
                        "Yes. Careers, recruitment, news, insights, and resource centre sections can be included within scope.",
                    ),
                ],
                related: vec![
                    related(
                        "Custom platform",
                        "Apex Custom",
                        "/packages/web-design-development/apex-custom",
                        "Use this when the website also needs bespoke platform or workflow engineering.",
                    ),
                    related(
                        "International expansion",
                        "Global Reach",
                        "/packages/web-design-development/global-reach",
                        "Use this when country, language, and international SEO structure are central.",
                    ),
                ],
                meta_title: "Flagship Premium Corporate Website Package | LKProfessionals",
                meta_description: "The Flagship starts from LKR 250,000 for corporations, institutions, NGOs, and established brands needing a premium corporate website.",
                icon: "fa-building-columns",
            },
            WebPackage {
                slug: "apex-custom",
                name: "Apex Custom",
                short_name: "Apex Custom",
                catalog_name: "Apex Custom - Bespoke Web Development Package",
                item_code: "LKP-WEB-AC-009",
                category: "Bespoke web engineering",
                price: "LKR 350,000+",
                price_number: "350000",
                positioning: "Bespoke web engineering where conventional websites are insufficient.",
                audience: vec![
                    "Enterprises",
                    "Organisations",
                    "Startups",
                    "Scale-ups",
                    "Businesses requiring custom platforms",
                    "Businesses requiring specialised workflows",
                ],
                core_message: "If your business can define it, we can engineer it.",
                description: "Apex Custom is for web applications, portals, dashboards, workflow systems, and bespoke platforms where a standard package is not enough.",
                inclusions: vec![
                    "Fully bespoke frontend and backend development",
                    "Custom UI/UX",
                    "Customer or client portals",
                    "User accounts and authentication",
                    "Role-based permissions",
                    "Custom admin dashboards",
                    "Database-driven functionality",
                    "Advanced forms and workflows",
                    "Booking or reservation systems",
                    "Payment gateways",
                    "Third-party APIs",
                    "CRM integrations",
                    "ERP integrations",
                    "Automated notifications",
                    "Reporting and analytics dashboards",
                    "Content management",
                    "Advanced search and filtering",
                    "Technical SEO foundations",
                    "On-page SEO foundations",
                    "Analytics and conversion tracking",
                    "Security/SSL",
                    "Performance optimisation",
                    "Production deployment and configuration",
                ],
                differentiator: "Individually scoped engineering for platforms, portals, dashboards, and specialised business workflows.",
                business_problem: "Your requirement is not just a website. You need custom logic, users, permissions, data, integrations, workflows, or reporting.",
                outcomes: vec![
                    "A scoped technical solution designed around real workflows",
                    "A maintainable production platform rather than a forced website template",
                    "A foundation that can connect with business systems where required",
                ],
                example_structure: vec![
                    "Discovery and technical scope",
                    "Custom frontend and backend",
                    "User roles and permissions",
                    "Data model and workflows",
                    "Admin dashboard",
                    "Integrations",
                    "Deployment and handover",
                ],
                addons: vec![
                    "Mobile applications",
                    "Advanced DevOps",
                    "Dedicated support plans",
                    "Security reviews",
                    "Complex third-party integrations",
                ],
                pricing_note: "Starting from LKR 350,000. This is not a fixed-scope application price; every Apex Custom project is individually scoped and quoted.",
                faqs: vec![
                    faq(
                        "Is LKR 350,000 a fixed application price?",
                        "No. Apex Custom starts from LKR 350,000. Every custom platform is individually scoped and quoted.",
                    ),
                    faq(
                        "Can Apex include portals and dashboards?",
                        "Yes. Client portals, admin dashboards, user accounts, permissions, and reporting dashboards are common fit areas.",
                    ),
                    faq(
                        "When should I choose Apex Custom?",
                        "Choose it when conventional website packages cannot cover the workflow, data, integration, or platform requirements.",
                    ),
                ],
                related: vec![related(
                    "Custom engineering",
                    "Discuss Scope",
                    "/request-quote",
                    "Apex Custom should be scoped through a consultation rather than treated as a normal tier upgrade.",
                )],
                meta_title: "Apex Custom Bespoke Web Development Package | LKProfessionals",
                meta_description: "Apex Custom starts from LKR 350,000 for bespoke web applications, portals, dashboards, workflows, integrations, and custom platform development.",
                icon: "fa-code-branch",
            },
            WebPackage {
                slug: "global-reach",
                name: "Global Reach",
                short_name: "Global Reach",
                catalog_name: "Global Reach - International & Multilingual Website Package",
                item_code: "LKP-WEB-GR-010",
                category: "International and multilingual website",
                price: "LKR 300,000+",
                price_number: "300000",
                positioning: "International and multilingual websites for businesses expanding across markets.",
                audience: vec![
                    "Exporters",
                    "International service providers",
                    "Tourism and travel companies",
                    "Education providers",
                    "Overseas recruitment businesses",
                    "Multinational organisations",
                    "Businesses expanding into new countries",
                ],
                core_message: "One website. Multiple markets. Global opportunity.",
                description: "Global Reach supports businesses expanding across countries, languages, or regions with multilingual structure, international SEO foundations, hreflang, localised CTAs, and enquiry routing.",
                inclusions: vec![
                    "Premium custom website",
                    "Multi-country architecture",
                    "Multilingual functionality",
                    "Country or regional landing pages",
                    "Language-specific content",
                    "International SEO foundation",
                    "SEO-friendly regional and language URL architecture",
                    "hreflang implementation",
                    "Location-specific services and content",
                    "Country-specific CTAs",
                    "International enquiry routing",
                    "Multi-currency presentation where required",
                    "Localised contact information",
                    "WhatsApp and social integration",
                    "Advanced CMS",
                    "Administration dashboard",
                    "Google Analytics",
                    "Google Search Console",
                    "Conversion and event tracking",
                    "Technical SEO",
                    "Performance optimisation",
                    "SSL/security",
                ],
                differentiator: "International architecture, multilingual content structure, hreflang, and market-specific conversion paths are planned together.",
                business_problem: "Your website needs to serve buyers across markets, languages, currencies, or regions without confusing users or search engines.",
                outcomes: vec![
                    "Clear country and language paths for international visitors",
                    "Search-friendly regional URL and hreflang foundations",
                    "Market-specific CTAs and enquiry routing",
                ],
                example_structure: vec![
                    "Global home",
                    "Country or region pages",
                    "Language-specific service pages",
                    "International contact routes",
                    "Market-specific CTAs",
                    "Advanced CMS",
                    "Analytics and Search Console setup",
                ],
                addons: vec![
                    "Professional translation",
                    "Local market copywriting",
                    "Advanced localisation workflows",
                    "International paid landing pages",
                    "Custom portals or platforms",
                ],
                pricing_note: "Starting from LKR 300,000. Final pricing depends on number of languages, countries, pages, localisation requirements, and integrations.",
                faqs: vec![
                    faq(
                        "Does Global Reach include multiple languages?",
                        "It can include multilingual functionality. Final scope depends on the number of languages, pages, and localisation requirements.",
                    ),
                    faq(
                        "Is hreflang included?",
                        "Yes. hreflang implementation is included where multilingual or regional versions require it.",
                    ),
                    faq(
                        "When should this move to Apex Custom?",
                        "If the international website also needs complex platform features, portals, or bespoke workflows, Apex Custom may be the better direction.",
                    ),
                ],
                related: vec![related(
                    "Highly custom international platform",
                    "Apex Custom",
                    "/packages/web-design-development/apex-custom",
                    "Use this when multilingual expansion also requires bespoke platform engineering.",
                )],
                meta_title: "Global Reach Multilingual Website Package | LKProfessionals",
                meta_description: "Global Reach starts from LKR 300,000 for exporters, tourism, education, recruitment, and international businesses needing multilingual websites.",
                icon: "fa-earth-asia",
            },
        ],
    }
}

pub fn find_web_package(slug: &str) -> Option<WebPackage> {
    web_design_family()
        .packages
        .into_iter()
        .find(|package| package.slug == slug)
}

fn faq(question: &'static str, answer: &'static str) -> PackageFaq {
    PackageFaq { question, answer }
}

fn related(
    label: &'static str,
    name: &'static str,
    href: &'static str,
    note: &'static str,
) -> RelatedPackage {
    RelatedPackage {
        label,
        name,
        href,
        note,
    }
}
